### ISSUE TITLE
Pre Run and Post Run chain functions 

### ISSUE THREAD

**Issue by algrebe** [spf13/cobra#219] opened 2016-01-08 07:11 UTC
W.r.t https://github.com/spf13/cobra/issues/216

Persitent\* functions execute only if the child has not overridden the parent.

Consider the following scenario:
Root command has a PersistentPreRun in which it defines a logger, sets the log level and starts a profiler.
Root command has a PersistentPostRun function in which it stops the profiler safely, closes file descriptors etc, whatever is needed for a clean and safe exit.

Child command also has a PersistentPreRun and PersistentPostRun for its own reasons - for its own child commands.
Since the child command has defined its own Persistent_, the root command Persistent_ are not called. 

To solve this, there need to be hooks that get fired irrespective of the child having its own hook - these are chain hooks.

PreRunChain gets called in the order of parent to child

PostRunChain gets called in the order of child to parent
i.e. root PreRunChain -> child PreRunChain

And PostRunChain gets called in the order of child to parent
i.e. child PostRunChain -> root PostRunChain

So for the previous scenario

root PreRunChain sets logger and profiler
child PreRunChain does its own initialization etc

```
/* the usual stuff that existed before - the overriding logic
PersistentPreRun
PreRun
Run
PostRun
PersistentPostRun
*/
```

child PostRunChain frees up its own things, for its safe exit
root PostRunChain stops the profiler

**Comment by henvic** [comment] 2016-12-27 17:13
When you have no Run for a given command and you end up printing the help for that given command: pre/post are silently skipped. This is the related [and not a feature], correct?

**Comment by bogem** [comment] 2017-10-30 14:38
Duplicate of #252

**Closed by bogem** 2017-10-30 14:38 UTC
