### ISSUE TITLE
[help] I broke Cobra

### ISSUE THREAD

**Issue by cdhunt** [spf13/cobra#454] opened 2017-05-25 14:09 UTC
I assume this is not a bug and I did something on my machine to break Cobra. I've tried deleting the Vendor folder and re-running Glide. I tried deleting the glide.yml and re-running `glide init`. I've tried `go get github.com/spf13/pflag`. Hopefully, someone can point me in a direction to resolve my failure. Thank you.

```
go build
# github.com/Ticketmaster/spinner/vendor/github.com/spf13/cobra
C:\Users\chris.hunt\go\src\spinner\vendor\github.com\spf13\cobra\command.go:419: fs.ShorthandLookup undefined (type *pflag.Fl
agSet has no field or method ShorthandLookup)
C:\Users\chris.hunt\go\src\spinner\vendor\github.com\spf13\cobra\command.go:1125: c.lflags.SortFlags undefined (type *pflag.F
lagSet has no field or method SortFlags)
C:\Users\chris.hunt\go\src\spinner\vendor\github.com\spf13\cobra\command.go:1125: c.Flags().SortFlags undefined (type *pflag.
FlagSet has no field or method SortFlags)
C:\Users\chris.hunt\go\src\spinner\vendor\github.com\spf13\cobra\command.go:1282: c.parentsPflags.SortFlags undefined (type *
pflag.FlagSet has no field or method SortFlags)
```

**Comment by bogem** [comment] 2017-05-25 15:48
Duplicate of #420.
If the solution there will not help you, don't hesitate to reopen the issue.

**Closed by bogem** 2017-05-25 15:48 UTC
