### ISSUE TITLE
Non-required flags not shown in tab completion until at least one required flag is set

### ISSUE THREAD

**Issue by bcongdon** [spf13/cobra#1061] opened 2020-03-16 22:02 UTC
For bash tab completion, if there exists a required flag and that flag has not been set, then no non-required flags are displayed in the tab completion list. Is this intended behavior?

https://github.com/spf13/cobra/blob/95f2f73ed97e57387762620175ccdc277a8597a0/bash_completions.go#L71-L74

For example, suppose I have 2 required flags `--req1` and `--req2` and one optional flag `--opt1`. (Suppose these are all string-valued flags)

**Actual behavior:**
Hitting tab after `mycmd --` yields suggestions for `--req1=` and `--req2=`. However, hitting tab after `mycmd --req1=foo --` yields suggestions for `--req2`  and `--opt1`.

**Expected behavior**:
I would expect that hitting tab after `mycmd --` would yield all three flags –  `--req1=`, `--req2=`, and `--opt1=` – as suggestions.

**Comment by marckhouzam** [comment] 2020-06-03 12:14
From what I have read in other issues and PRs, this is the expected behavior.  However, I agree it could be improved upon.

First, it was an oversight that a second required flag isn't given priority.  In the above example, `mycmd --req1=foo --[tab][tab]` should only suggest `--req2`.  I believe this is how the current zsh completion behaves, and how #1070 behaves for both zsh and fish. In my mind, this could be fixed for bash.

Second, it could be argued that if the user has typed the `-` or `--` prefix, then all flags should be shown in completion, not just the required ones. The advantage is that it allows the user to use completion to list all flags to learn about them.  The disadvantage is that it requires the user to type more letters to be able to complete the required flags.  So it could be argued both ways.

**Comment by johnSchnake** [comment] 2022-03-29 16:06
> First, it was an oversight that a second required flag isn't given priority. In the above example, mycmd --req1=foo --[tab][tab] should only suggest --req2. I believe this is how the current zsh completion behaves, and how https://github.com/spf13/cobra/pull/1070 behaves for both zsh and fish. In my mind, this could be fixed for bash.

Leaving this open with a 'needs-pr' tag since the scope of the problem has been specified and this would make it consistent with the zsh implementation.

**Comment by johnSchnake** [comment] 2022-03-29 16:06
> First, it was an oversight that a second required flag isn't given priority. In the above example, mycmd --req1=foo --[tab][tab] should only suggest --req2. I believe this is how the current zsh completion behaves, and how https://github.com/spf13/cobra/pull/1070 behaves for both zsh and fish. In my mind, this could be fixed for bash.

Leaving this open with a 'needs-pr' tag since the scope of the problem has been specified and this would make it consistent with the zsh implementation.

**Comment by marckhouzam** [comment] 2022-03-29 16:27
To clarify the answer to the main question of this issue: 

> For bash tab completion, if there exists a required flag and that flag has not been set, then no non-required flags are displayed in the tab completion list. Is this intended behavior?

Yes, this looks like the intended behaviour from the very first shell completion PR #69.
Since it's been like that from the start, we probably should leave it as is.

Another thing to clarify is that since this issue was opened, Cobra now provides a [bash completion V2 solution](https://github.com/spf13/cobra/blob/master/shell_completions.md#bash-completion-v2) which completes all required flags first.  So all shells now behave the same. 

The legacy bash completion V1 still has the bug so we can leave the issue open, but I wonder how much willingness there will be to put effort into changing it or even reviewing such a change now that it is considered legacy.

(The last comment from @johnSchnake was present twice for some reason, I deleted the second identical copy.)

**Comment by marckhouzam** [comment] 2022-09-30 18:23
As we are not actively making improvement to the legacy bash completion logic and that bash completion V2 (as well as the other shells) behave as expected, I'm going to close this.

Please re-open if you feel more improvements are required.

**Closed by marckhouzam** 2022-09-30 18:23 UTC
Labels: kind/support, area/shell-completion, lifecycle/needs-pr
