### ISSUE TITLE
How to have sub commands "share" a sub command?

### ISSUE THREAD

**Issue by gschouse** [spf13/cobra#492] opened 2017-07-18 17:52 UTC
I am creating a tool to work with a bunch of microservices. I want to perform operations on each service, such as a `list`, as some of these services will have information needed to list about them. Example use of the tool, calling the tool `tool`:

`tool service1 list`

Suppose I have `service1`, `service2`, and `service3` as subcommands of `tool`. How can I allow these to each have a `list` child command, without having to create multiple explicit children commands, such as `service1List`, `service2List`, etc?

**Comment by bogem** [comment] 2017-07-18 18:01
Duplicate of #362

**Closed by bogem** 2017-07-18 18:01 UTC
