### ISSUE TITLE
Subcommand Group   panic: Group id 'Group1' is not defined for subcommand 'app1 sub1'

### ISSUE THREAD

**Issue by KINGSABRI** [spf13/cobra#1830] opened 2022-10-16 18:59 UTC
Hi everyone 
I'm trying to implement to 
- root.go
```go
func init() {
	cobra.EnableCaseInsensitive = true
	cobra.EnableCommandSorting = false

	rootCmd.CompletionOptions.DisableDefaultCmd = true 
	rootCmd.Flags().SortFlags = false
	rootCmd.PersistentFlags().SortFlags = false

	rootCmd.AddGroup(&cobra.Group{ID: "Group1", Title: "Group1 Subcommands:"})
}
```

- sub1.go

```go
var sub1Cmd = &cobra.Command{
	Use:     "sub1",
	GroupID: "Group1",
	Aliases: []string{"1"},
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("Hiii")
	},
}

func init() {
	rootCmd.AddCommand(sub1Cmd)
	sub1Cmd.Flags().SortFlags = false
	sub1Cmd.Flags().StringP("ipaddress", "i", "0.0.0.0", "IP address to listen to")
}

```

**Comment by marckhouzam** [comment] 2022-10-17 12:29
Duplicate of #1831

**Closed by marckhouzam** 2022-10-17 12:29 UTC
