### ISSUE TITLE
Exit with code 0 when invalid subcommand is passed

### ISSUE THREAD

**Issue by ldufresnegs** [spf13/cobra#2034] opened 2023-09-28 07:40 UTC
Hey, I might be missing something completely, but there seems to be a undesirable behavior when an invalid sub-command is passed. Indeed, the help is shown, but the exit code is 0.

The following code early exit when there is the error is `flag.ErrHelp` which I assume is meant for when the `-h` is passed, but also happen when an invalid sub-command is passed. https://github.com/spf13/cobra/blob/bd4d1655f6655f690f45d281fe698dacb9c7d750/command.go#L1094-L1097

Indeed, in `execute()`, there is the following: https://github.com/spf13/cobra/blob/bd4d1655f6655f690f45d281fe698dacb9c7d750/command.go#L918-L920

I'm I missing something? It seems that the desirable behavior would be to return an error when an invalid sub-command is passed.

~~The only workaround that may work is to call `ExecuteC` and check that the returned sub-command is not the root command.~~
Edit: Nevermind, can't distinguish with an `--help` flag.

**Comment by marckhouzam** [comment] 2023-09-28 10:24
Duplicate of #1156

**Closed by marckhouzam** 2023-09-28 10:24 UTC
