### ISSUE TITLE
When the value of PersistentFlags is the same as the name of the subcommand, it will have issue

### ISSUE THREAD

**Issue by yxxhero** [spf13/cobra#1834] opened 2022-10-20 00:06 UTC
I have a `test` subcommand and a Persistent Flag `-e`.
```
rootcmd -e test -l name=catalyst test
```

`-e` will be `-l` value.

what should I do to solve this issue?

Thanks very much.

**Comment by yxxhero** [comment] 2022-10-20 01:37
```go
package main

import (
	"fmt"

	"github.com/spf13/cobra"
)

func main() {
	var env string
	var selector string

	var cmdEcho = &cobra.Command{
		Use: "test",
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Println(env, selector)
		},
	}

	var rootCmd = &cobra.Command{Use: "app"}
	rootCmd.PersistentFlags().StringVarP(&env, "env", "e", "", "env")
	rootCmd.PersistentFlags().StringVarP(&selector, "selector", "l", "", "selector")

	rootCmd.AddCommand(cmdEcho)
	_ = rootCmd.Execute()
}
```

```bash
[root@devops gotest]# go run main.go -e test -l a=b test
-l 

```

@marckhouzam Thanks for your feedback.
I think it is a bug.

**Comment by yxxhero** [comment] 2022-10-20 01:38
```bash
[root@devops gotest]# go run main.go -e=test -l=a=b test
test a=b
```
this is work fine.

**Comment by marckhouzam** [comment] 2022-10-20 01:59
Thanks @yxxhero I can reproduce the bug.
I don't have time to debug right now, but we'll need to run the debugger on it.  I suspect a problem in `cobra.stripFlags()`

**Comment by marckhouzam** [comment] 2022-10-20 02:07
Actually, I just remembered this issue a duplicate off #1777  which has a PR posted.

**Closed by marckhouzam** 2022-10-20 02:07 UTC
Labels: kind/bug, area/flags-args
