### ISSUE TITLE
Could the cobra show deprecated message in the help output

### ISSUE THREAD

**Issue by yuexiao-wang** [spf13/cobra#566] opened 2017-11-04 15:21 UTC
Could the cobra show deprecated message in the help output? 

for example
$ kubectl.sh exec -h | grep -e '-p'
-p POD_NAME is DEPRECATED and will be removed in a future version. Use exec POD_NAME instead.

**Comment by yuexiao-wang** [comment] 2017-11-04 15:22
@bogem PTAL

**Comment by bogem** [comment] 2017-11-04 16:55
Not yet. Planned in v2.0.0.
It's actually a duplicate of #358.

**Closed by bogem** 2017-11-04 16:55 UTC

**Comment by yuexiao-wang** [comment] 2017-11-18 06:12
@bogem when will be released for v2.0.0?
