### ISSUE TITLE
Fish completions script is fairly slow; `glab` takes 140ms

### ISSUE THREAD

**Issue by max-sixty** [spf13/cobra#1855] opened 2022-11-15 06:26 UTC
I was directed here from https://gitlab.com/gitlab-org/cli/-/issues/1098#note_1171752320. 

I'm not that familiar with `cobra` unfortunately, so most of my report is just the content of that issue. It shows that sourcing the `glab` completions is much slower than any other completions, and that work is being done in the hot path.

Let me know if any other info would be helpful. Many thanks!

**Comment by marckhouzam** [comment] 2022-11-15 11:03
What you should first try @max-sixty would be to avoid sourcing the script at every shell startup and to instead do this once manually:
```
glad completion fish > ~/.config/fish/completions/glab.fish
```

For the discussion however the slowdown is probably caused by this part, as you identified in the original issue: https://github.com/spf13/cobra/blob/ad6db7f8f6e485f55b1561df9276fa4d8e278bde/fish_completions.go#L194-L206

What this does is load any completion script included directly in fish and delete its completions to only leave the completions generated by Cobra.

This was to protect against old versions of completions script provided directly by fish. I'm not sure how much of a problem this actually is...

**Comment by max-sixty** [comment] 2022-11-16 01:27
> What you should first try @max-sixty would be to avoid sourcing the script at every shell startup and to instead do this once manually:
> 
> ```
> glab completion fish > ~/.config/fish/completions/glab.fish
> ```

Great idea! This solves the vast majority of the issues. Obv would be even better for the completion itself to be fast, but that's far more minor. Feel free to close.

**Comment by max-sixty** [comment] 2022-11-16 01:29
To the extent that guidance could be given to library authors, that would mean they'd suggest the right thing to users; for example `glab` suggests this in their help:

```
For example, for bash you could add this to your '~/.bash_profile':

        eval "$(glab completion -s bash)"
```

I'll add this comment to the issue over there too

**Comment by marckhouzam** [comment] 2022-11-16 01:58
FYI, Cobra provides a default `completion` command if programs don't provide one themselves.  In the help text of that command Cobra guides the user as you can see for fish here: https://github.com/spf13/cobra/blob/ad6db7f8f6e485f55b1561df9276fa4d8e278bde/completions.go#L762-L770

Since the proposed solution is satisfactory I'll go ahead and close this.

**Closed by marckhouzam** 2022-11-16 01:58 UTC
Labels: area/shell-completion

**Comment by krobelus** [comment] 2022-11-16 21:03
instead of the `complete -C` call, you could run

```fish
set -l tmpdir (mktemp -d)
set -l fish_complete_path $tmpdir
touch $tmpdir/glab.fish
complete -C "glab "
rm -r $tmpdir
```

before you define the actual completions for `glab`.
The `complete -C "glab "` command will make fish load the empty `glab.fish` and add an internal tombstone that will prevent it from loading completions for `glab` again (untested).

Related fish issue is https://github.com/fish-shell/fish-shell/issues/6716

**Comment by max-sixty** [comment] 2022-11-16 21:31
I don't have much context so forgive the naive question — but is it a common problem that there are conflicting autocompletions, such that we need to clear existing completions on each invocation? Where would the other `glab` ones be from?

**Comment by krobelus** [comment] 2022-11-16 21:43
the source of the problem is that `go install` cannot install completion files.
If the user installs `glab` with their package manager, that might add a completion file. Or in some cases, fish ships the completion file.
Now if the user installs a newer version with `go install` or similar, it'd still be using the old completion file.
Granted, it makes no difference in many cases but historically it was important to get the version that was built with latest cobra.

**Comment by max-sixty** [comment] 2022-11-17 00:45
OK, I still can't completely visualize how that's a big issue — presumably someone can remove the source of the old completions, whether that's a file or a call in their `config.fish`? But my issue is solved and appreciate the engagement. Thanks @krobelus
