### ISSUE TITLE
Cannot go get without specifying version number

### ISSUE THREAD

**Issue by ImSingee** [spf13/cobra#1223] opened 2020-09-10 02:11 UTC
If I use the command from documentation

```
go get -u github.com/spf13/cobra/cobra
```

I can't download the package successfully, I got an error message like 

```
go: downloading github.com/spf13/cobra/cobra v0.0.0-20200909172742-8a63648dd905
go: github.com/spf13/cobra/cobra upgrade => v0.0.0-20200909172742-8a63648dd905
go get github.com/spf13/cobra/cobra: ambiguous import: found package github.com/spf13/cobra/cobra in multiple modules:
        github.com/spf13/cobra v1.0.0 (C:\Users\admin\go\pkg\mod\github.com\spf13\cobra@v1.0.0\cobra)
        github.com/spf13/cobra/cobra v0.0.0-20200909172742-8a63648dd905 (C:\Users\admin\go\pkg\mod\github.com\spf13\cobra\cobra@v0.0.0-20200909172742-8a63648dd905)
```

If I use

```
go get -u github.com/spf13/cobra/cobra@v1.0.0
```

The problem solved.

**Comment by jharshman** [comment] 2020-09-23 21:36
This sounds related to #1191 which should have been fixed.

**Comment by jharshman** [comment] 2020-09-23 21:38
duplicate of #1215

**Closed** 2020-09-23 21:38 UTC
Labels: needs investigation
