### ISSUE TITLE
add named arguments to the use line

### ISSUE THREAD

**Issue by georgettica** [spf13/cobra#1666] opened 2022-04-13 07:02 UTC
# Purpose
As a  cobra user, I would like to add named arguments (maybe even in the `LongDescription` explain more on them) so they will show up when I run the `--help` on the created command

# Current state
I need to add to the `Use` my arguments or override the whole line with `UseLine`

https://github.com/spf13/cobra/blob/5b2b9e9f61d36ccb66167301f76a2292c3729855/command.go#L1245

this is related to https://github.com/openshift/osdctl/pull/206

**Comment by johnSchnake** [comment] 2022-04-15 14:52
Duplicate of https://github.com/spf13/cobra/issues/378

That issue has some interest but since it could be an issue with larger scope I thought it warranted a more thorough design if you're interested in taking that on.

**Closed by johnSchnake** 2022-04-15 14:52 UTC
Labels: kind/feature, area/docs-generation
