### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by fd0** [spf13/cobra#495] opened 2017-07-23 07:16 UTC
For [restic](https://github.com/restic/restic), we'll switch to `dep` shortly, and it would be very helpful if you could tag a release. Thanks!

https://dave.cheney.net/2016/06/24/gophers-please-tag-your-releases

**Comment by bogem** [comment] 2017-07-23 07:23
Duplicate of #259

**Closed by bogem** 2017-07-23 07:23 UTC

**Comment by fd0** [comment] 2017-07-23 07:25
Ah, sorry, I must've overlooked that one.

**Comment by bogem** [comment] 2017-07-23 07:31
AFAIK in dep you can add dependencies even without tags, but to certain commits.
