### ISSUE TITLE
backslashes in default string values get doubled up

### ISSUE THREAD

**Issue by 06kellyjac** [spf13/cobra#1396] opened 2021-05-11 08:42 UTC
If you have a string with backslashes (correctly escaped to be a  literal `\`) if it's the cobra default value it outputs with extra slashes, presumably for escaping.

`flags.StringVar(&opts.something, "the-flag", "ping\\pong", "The description") `
outputs with an extra slash:
`--the-flag string              The description (default "ping\\pong")`

`fmt.Sprintf("my string: %s", "ping\\pong")`
outputs the correct amount of slashes:
`my string: ping\pong`

Is there a reason for the extra slashes? or is this unintended?

I tried looking for old issues but I couldn't find anything

**Comment by 06kellyjac** [comment] 2021-07-11 08:04
Still important

**Comment by johnSchnake** [comment] 2022-03-16 05:39
Reproduced and agree it should print the single slash.

**Comment by johnSchnake** [comment] 2022-03-16 05:45
Just spent another minute looking at this and that I think it is caused from the pflag library here https://github.com/spf13/pflag/blob/85dd5c8bc61cfa382fecd072378089d4e856579d/flag.go#L733

The %q is what causes it to be a go-escaped string rather than just using `"%v"`; go fmt package states that %q for strings as:
```
%q	a double-quoted string safely escaped with Go syntax
```

So I think we need to put a PR up for that. I'll create an issue there to track it.

**Comment by johnSchnake** [comment] 2022-03-16 06:05
PR: https://github.com/spf13/pflag/pull/347
Going to close this issue since I've created the other issue/PR and there isn't anything to track here.

**Closed by johnSchnake** 2022-03-16 06:05 UTC
Labels: kind/bug, good-first-issue, area/docs-generation, lifecycle/needs-pr

**Comment by rohitramu** [comment] 2023-08-21 00:28
I'm still seeing this issue.  Looks like spf13/pflag#347 still hasn't been merged.
