### ISSUE TITLE
reusing flags for subcommand.

### ISSUE THREAD

**Issue by kunalkushwaha** [spf13/cobra#277] opened 2016-05-17 05:01 UTC
same Flags should be allowed to be reuse in sub-commands.

Problem:
- few flags like `-f` are synonymous to `--force` or `--file` flags. 
- Since usage of same flag is not allowed in one command tree (command, sub-commands), changing UX is required, which is not good as per UX design.

**Comment by murphyke** [comment] 2016-07-29 18:20
Does this mean that you can't have `cmd sub1 -f` and `cmd sub2 -f` (with other subcommands not using `-f` at all)?  If so, that is a painful restriction.

If you turned `-f` into a global switch, that would be  misleading, and you'd have to manually flag an error in the subcommands not using `-f`.  Yuck.

**Comment by bogem** [comment] 2017-04-19 12:06
Can you please more describe your problem?

**Comment by dnephin** [comment] 2017-04-19 15:01
I had this problem as well. It's fixed in #299 by setting `TraverseChildren = true`.

The problem is that the current behaviour of cobra is to have only a single pool of flags, which you specify on the final command.

Many command line tools expect different flags for each command level. For examples:

```
mycommand  -f filename subcommand -f filter
```

**Comment by bogem** [comment] 2017-04-20 08:33
What's the problem just to add flags with different names? 
Flags with same name/shorthands like `mycommand  -f filename subcommand -f filter` make CLI programs ambiguous and more complex to understand. Also #299 adds a complexity to code.

**Comment by dnephin** [comment] 2017-04-20 14:16
Regardless of what you might think about putting flags on subcommand this is a common pattern in CLIs. So either cobra is not capable of  creating such CLIs, or there needs to be a code change.

If there are issues with the code in #299 please do comment on that PR. I'm sure we can reduce the complexity.

**Comment by spf13** [comment] 2017-04-21 21:28
@dnephin Thanks for this suggestion.

Fundamentally I think having flags & arguments on parent commands adds significantly to the complexity and reduces the usability of applications. Cobra is very flexible but also opinionated. We encourage developers to make good usability decisions with their application designs. 

Can you help me (and @bogem it appears) better understand the use case for this that isn't met with the current designs?

You state that 
> Many command line tools expect different flags for each command level. 

Can you provide concrete examples?

**Comment by dnephin** [comment] 2017-04-21 21:39
The first example is easy. The code that implements this feature ( #299) is already used in `docker` because that's how flags worked in the CLI before we moved to using cobra. The flags on `docker` are not the same flags on `docker subcommand`.

The [aws cli](https://aws.amazon.com/cli/) is another example of this.

I'm sure I can find more if I look around. I would imagine that nearly every CLI that has multiple subcommands would behave this way.  Maybe the OP has another example for us as well.

**Comment by dnephin** [comment] 2017-04-21 21:44
Oh, and of course `git` is another great example of this!

**Comment by bogem** [comment] 2017-04-21 23:09
Can you please show a concrete command of git, where there are flags with the same names?

**Comment by dnephin** [comment] 2017-04-21 23:10
```
git -p add -p
```

the first `-p`  is about pagination, the second is "patch"

**Comment by dnephin** [comment] 2017-04-22 21:31
I think the more important point isn't about re-using flags, it's about where flags can be specified. For example this command is not valid:

```
$ git mv -p
error: unknown switch `p'
```

Because `git mv` does not have a `-p` flag. The flags that are on parent commands are irrelevant.

This is the behaviour I would expect from every CLI. It seems like Cobra has taken a different approach, but with this change I believe both options can be supported.

**Comment by murphyke** [comment] 2017-04-24 14:54
I also vote for flexibility, and I have the same CLI expectations as dnephin, perhaps through use of big tools like git (and decades of *nix CLI work). Although it seems like it might be bad design for parent and child commands to take short flags with different meanings, I am thinking about why short flags are implemented at all. Presumably they are implemented for people who use the flags frequently at the command line and are thus in a mental position to keep things straight. Most tools do not provide a short flag for every option -- just the ones that are most likely to be used very frequently. It seems like a very surprising limitation to me to not allow parent and child commands to implement the same short flag.

**Comment by dnephin** [comment] 2017-06-15 20:05
Another request for this in #467

**Closed** 2017-10-07 21:29 UTC
