### ISSUE TITLE
Unable to build lastest version of master using glide

### ISSUE THREAD

**Issue by pmonk4657** [spf13/cobra#539] opened 2017-10-04 10:56 UTC
Operating System: ubuntu 16.04
Go version: 1.8.3
Glide version: 0.12.3

steps to reproduce:

- use `spf13/cobra` in a package
- `glide init` ('N' to improving glide.yaml configuration)
- `glide install`
- `go build`

failed build output:
`
vendor/github.com/spf13/cobra/command.go:422: fs.ShorthandLookup undefined (type *pflag.FlagSet has no field or method ShorthandLookup)
vendor/github.com/spf13/cobra/command.go:1134: c.lflags.SortFlags undefined (type *pflag.FlagSet has no field or method SortFlags)
vendor/github.com/spf13/cobra/command.go:1134: c.Flags().SortFlags undefined (type *pflag.FlagSet has no field or method SortFlags)
vendor/github.com/spf13/cobra/command.go:1298: c.parentsPflags.SortFlags undefined (type *pflag.FlagSet has no field or method SortFlags)
`

The issue seems to be with the `spf13/pflag` library. Probably a versioning issue.

my glide is automatically picking up the following versions:
- `spf13/cobra`: `3c0b56b677e04926dfa835a1b3f11cd4f62f076e`
- `spf13/pflag`: `9ff6c6923cfffbcd502984b8e0c80539a94968b7`

**Comment by bogem** [comment] 2017-10-04 11:31
Duplicate of #420. Here is the solution: https://github.com/spf13/cobra/issues/420#issuecomment-296359451

**Closed by bogem** 2017-10-04 11:31 UTC
