### ISSUE TITLE
Did cobra consider adding multiple languages

### ISSUE THREAD

**Issue by 0x9527-zhou** [spf13/cobra#1842] opened 2022-10-25 09:05 UTC
Cobra is a very convenient command line tool, but now there is only one language format. In my opinion, a world-class framework should also support more language types. I hope you can consider it.

**Comment by marckhouzam** [comment] 2022-10-25 10:28
Multi-language support world new great but no one in the community has proposed a PR yet.

Duplicate of #1134 .

**Closed by marckhouzam** 2022-10-25 10:28 UTC
