### ISSUE TITLE
Default version flag is missing

### ISSUE THREAD

**Issue by Fjolnir-Dvorak** [spf13/cobra#490] opened 2017-07-17 21:04 UTC
I am missing the default flag `--version` to get the version of the programm defined in [https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html](https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html). It is a flag that is recommended to be implemented by every program, just like the help flag `--help`

**Comment by Fjolnir-Dvorak** [comment] 2017-07-17 21:34
Auto versioning is not possible in plain old go. I wonder if that was the reason to ignore or forget the version flag. But it is archievable with a makefile reading all needed git informations and handling the build- and version number.
Considering that the flag "version" is a standard and should be supported, is it an option to solve this problem with makefiles? There are makefiles for windows and for linux at least. I do not know of any proper way to compile a Go application without the help of make or shell/bash/ps scripting.
I do not know anything about make, but I could look into it and could create a new merge request or extend my existing one.

It is only interesting for new generated projects so backwards compability is not an issue. Those who are using Cobra already, will sadly not get any improvement by this feature.

**Comment by bogem** [comment] 2017-07-18 05:58
Duplicate of #282

**Closed by bogem** 2017-07-18 05:58 UTC
