### ISSUE TITLE
Required Persistent Flags are enforced on the help command

### ISSUE THREAD

**Issue by bit101** [spf13/cobra#1096] opened 2020-04-20 23:04 UTC
Steps:
1. In a bare cobra app, create a persistent flag named `foo`. Whatever type you want.
2. Mark it as required.
3. Add a `bar` command.
4. Compile and run `appname help bar`

Result: it will tell you that you are missing the required `foo` flag.

Expected: required flags should not be checked on the `help` command.

Is there any workaround?

**Comment by marckhouzam** [comment] 2020-04-20 23:36
I haven't tried to reproduce but I just posted a fix for something very similar for commands that user DisableFlagParsing.  We could do something similar for your case. See #1095

**Comment by bit101** [comment] 2020-04-21 00:40
Thanks. I just started digging into Cobra this weekend, so not very familiar with the internals. Otherwise I would probably have had a go at fixing it myself.

**Comment by marckhouzam** [comment] 2020-04-21 00:41
I confirm that I can reproduce this problem with the master branch.

@bit101 Can you explain your use case? I'm asking because the problem you describe will only happen if you set a required persistent flag on the **root** command.  This seems like an unusual thing to do in my mind.  It would imply that the flag in question would have to be used all the time, for every sub-commands possible.

**Comment by bit101** [comment] 2020-04-21 00:48
Yes, that's what I was doing. Again, just started using Cobra, so if this is not a normal pattern, it could be an edge case. Now that I think of it, my sub-commands might be better off as args as they are all performing similar actions.

**Comment by bit101** [comment] 2020-04-21 00:49
This would also explain why nobody else reported what seemed an obvious bug to me. :)

**Comment by johnSchnake** [comment] 2022-02-17 15:41
Seems to have been fixed:

```
➜  ./tmp child
Error: required flag(s) "other" not set
Usage:
  cmd child [flags]

Flags:
  -h, --help           help for child
      --other string   usage string

Global Flags:
      --name string   usage string

➜  ./tmp help child
Usage:
  cmd child [flags]

Flags:
  -h, --help           help for child
      --other string   usage string

Global Flags:
      --name string   usage string
```

Closing; if you're still experiencing the problem please reopen and let us know.

**Closed by johnSchnake** 2022-02-17 15:41 UTC
Labels: kind/bug, needs investigation, needs PR
