### ISSUE TITLE
PrintErrln & PrintErrf prints to stdout

### ISSUE THREAD

**Issue by bukowa** [spf13/cobra#1220] opened 2020-09-08 10:26 UTC
`PrintErr` prints to `ErrOrStderr` but `PrintErrln` and `PrintErrf` prints using `Print` which prints to `OutOrStderr`.

https://github.com/spf13/cobra/blob/02a0d2fbc9e61d26f8e5979749f6030964a55a3e/command.go#L1190-L1193
https://github.com/spf13/cobra/blob/02a0d2fbc9e61d26f8e5979749f6030964a55a3e/command.go#L1205-L1218

Thats how it is now:
````golang
// PrintErrln is a convenience method to Print to the defined output, fallback to Stderr if not set. 
// PrintErrf is a convenience method to Print to the defined output, fallback to Stderr if not set. 
````

**Comment by marckhouzam** [comment] 2020-09-08 10:40
Duplicate of #1100. 
Possible fix at #894

**Closed** 2020-09-08 10:53 UTC
