### ISSUE TITLE
Init does not work with a GOPATH with multiple workspaces

### ISSUE THREAD

**Issue by burdiyan** [spf13/cobra#569] opened 2017-11-06 09:15 UTC
$GOPATH environmental variable can specify multiple workspace, as $PATH can. For example `GOPATH=/code/foo:/code/bar`. More on that in this post: https://dmitri.shuralyov.com/blog/18

In this case, when you do `go get github.com/spf13/cobra` in will be installed in the first workspace. Then when you run `cobra init baz` inside a directory in the second workspace, Cobra will fail with: `Error: Cobra only supports project within $GOPATH` and that directory `baz` will be created with LICENSE file only.

Desired behaviour: `cobra init` should be able to create projects inside any part of the $GOPATH.

**Comment by burdiyan** [comment] 2017-11-06 09:21
BTW, the same error will happen if you try to run `cobra init` in the first workspace of the GOPATH.

**Comment by bogem** [comment] 2017-11-06 09:24
You use old version of cobra/cmd. It is already fixed in #428. Please update the library: `go get -u github.com/spf13/cobra`.
Duplicate of #276.

**Closed by bogem** 2017-11-06 09:24 UTC

**Comment by burdiyan** [comment] 2017-11-06 11:50
My bad! I would swear I updated it before submitting the issue, but I might have missed something. Sorry.
