### ISSUE TITLE
When using a space to separate flags and values, the value in NoOptDefVal is always used

### ISSUE THREAD

**Issue by galjoey** [spf13/cobra#1962] opened 2023-05-24 12:48 UTC
When using the option NoOptDefVal for flags to enable users to use a flag both as a switch and as a configuration, if the user provides the flag and value in the format `--flag=value` or `-f=value` NoOptDefVal works as expected, however when using a space to separate the flag and value the value is treated as missing even when supplied and the value in NoOptDefVal is applied instead.
Cobra Version: 1.7.0
OS: Windows 10

Assuming the below code:

```
func main() {
	execute := &cobra.Command{
		Use:   "execute",
		Short: "execute this test",
		Long:  "run the demo code to execute this test",
		Run:   func(cmd *cobra.Command, args []string) { fmt.Println(cmd.Flag("name").Value) },
	}
	execute.Flags().StringP("name", "n", "novalue", "specify the name")
	execute.Flag("name").NoOptDefVal = "noopt"

	execute.Execute()
}
```

When invoking the command `go run cobra-demo -n=test` the output is `test` as expected 

When invoking the command `go run cobra-demo -n test` the output is `noopt`, however the expected output is `test`

**Comment by jon4hz** [comment] 2023-06-09 18:44
I'm having the same issue with cobra v1.7.0 on linux.

**Comment by marckhouzam** [comment] 2023-06-10 20:55
I believe this is correct behavior. When setting the `NoOptDefVal` field for a flag then only the `=` form can be used.

The `NoOptDefVal` field is used to specify a value when the flag is on the command line without any value. For example `cobra-demo -n`.  But when this is enabled and the user provides `cobra-demo -n test`, how can cobra know if `test` is a value for the flag or an argument to the command?  It cannot.

So, when `NoOptDefVal` is set, then only the `=` form can be used.

**Comment by marckhouzam** [comment] 2023-06-10 21:01
Duplicate of #866

**Closed by marckhouzam** 2023-06-10 21:01 UTC
