### ISSUE TITLE
Error: Cobra only supports project within $GOPATH

### ISSUE THREAD

**Issue by dalu** [spf13/cobra#491] opened 2017-07-18 15:08 UTC
```
$ env | grep GO
GOPATH=/home/darko/3go:/home/darko/go
```
why this?
Apparently it leads to `go get` downloads being saved to 1st path option and I can have my stuff inside my GOPATH (2nd option).

However
```
darko@dev ~/go/src/git.icod.de/dalu/jokes $ cobra init
Using config file: /home/darko/.cobra.yaml
Error: Cobra only supports project within $GOPATH
```

**Comment by bogem** [comment] 2017-07-18 15:23
It's already fixed.
Please update cobra cmd ('go get -u github.com/spf13/cobra/cobra').
Duplicate of #330.

**Closed by bogem** 2017-07-18 15:23 UTC

**Comment by dalu** [comment] 2017-07-18 15:33
```
darko@dev ~/go/src/git.icod.de/dalu/jokes $ cobra init
Using config file: /home/darko/.cobra.yaml
Error: Cobra will not create a new project in a non empty directory: /home/darko/go/src/git.icod.de/dalu/jokes
darko@dev ~/go/src/git.icod.de/dalu/jokes $ l
total 12K
drwxr-xr-x 3 darko darko 4,0K 18. Jul 17:31 .
drwxr-xr-x 7 darko darko 4,0K 18. Jul 16:49 ..
drwxr-xr-x 5 darko darko 4,0K 18. Jul 17:30 .idea
```
This wasn't the case previously.
Why would "hidden" dirs be a problem?

**Comment by bogem** [comment] 2017-07-18 16:23
Fixed in https://github.com/spf13/cobra/commit/715f41bd7a70b5111f898b71ab484da52ee6266d. Thanks for this!
