### ISSUE TITLE
Remove timestamp in generated documentation

### ISSUE THREAD

**Issue by adrienkohlbecker** [spf13/cobra#142] opened 2015-09-03 23:59 UTC
Hello,

First of all, thanks for the time you put in this library, I find it really useful.

I'd like to setup a commit hook for my team, to automatically update the documentation (using both markdown and man). 
This works, however there is a timestamp in the generated docs which prevents me to roll it out (namely, every commit now has a diff in the docs).
`###### Auto generated by spf13/cobra at 2015-09-03 23:32:45.933601388 +0000 UTC`

Would it be okay for you guys to remove it? 
I was going to suggest a configuration option but it would seem overly complicated here :)

Best

**Comment by spf13** [comment] 2015-11-06 16:12
Make a PR with a flag to not timestamp.

**Comment by apriendeau** [comment] 2015-11-23 04:43
@spf13 @eparis Is this still valid?

**Comment by anthonyfok** [comment] 2015-11-23 06:19
Hi @apriendeau,

Thanks for pointing out that this issue has been fixed in Cobra.  As a matter of fact, your new flag is already being used in Hugo as of 14 hours ago :wink:, see:

* https://github.com/spf13/hugo/blob/master/commands/genman.go#L20

I am using this flag for Hugo's man page generation because it seems the idea of [Reproducible Builds](https://reproducible-builds.org/) is in these days, and the major Linux distributions like Arch Linux, Debian, Fedora etc. are behind it, so I am sure sooner later someone will ask me to remove the every-time-is-different autogen tag...  :stuck_out_tongue: 

Closing this issue.  (If I missed anything, please feel free to re-open it.)

**Closed by anthonyfok** 2015-11-23 06:19 UTC

**Comment by apriendeau** [comment] 2015-11-23 07:08
Well that's awesome, that something I did is getting put to good use. Just
was looking for new bugs to grab and saw this still so I thought I would
mention it. Thanks for closing it.

**Comment by anthonyfok** [comment] 2015-11-23 07:48
Thank you for your contribution, @apriendeau!  :-)
