### ISSUE TITLE
Developing a command line program that can run continuously based on Cobra

### ISSUE THREAD

**Issue by feiquan666** [spf13/cobra#2048] opened 2023-10-17 09:07 UTC
Assuming my application name is app, the usual usage is `app -- version` to obtain version information and `app -- help` to obtain help. But I don't want to do this. What I hope is that after starting with the app, it will be a separate application, and then I can directly enter `help` or `version` to obtain the desired results. The program will continue to wait for my input and will not exit after execution.

Because every time I input the app, it's a bit annoying

for example

```
user ~%  app start
app>>  help
app>>  help message
app>>  version
app>>  version is 1.0.1, powerd by cobra
```

**Comment by marckhouzam** [comment] 2023-10-17 10:26
Duplicate of #1440

**Comment by feiquan666** [comment] 2023-10-17 10:35
thank you very much

**Closed** 2023-10-17 10:35 UTC
